const QUOTES = [
  { text: "Der beste Weg, die Zukunft vorherzusagen, ist sie zu gestalten.", author: "Peter Drucker" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
  { text: "Simplicity is the soul of efficiency.", author: "Austin Freeman" },
  { text: "Code is like humor. When you have to explain it, it's bad.", author: "Cory House" },
  { text: "Der einzige Weg, gute Arbeit zu leisten, ist zu lieben, was man tut.", author: "Steve Jobs" },
  { text: "Programs must be written for people to read, and only incidentally for machines to execute.", author: "Harold Abelson" },
  { text: "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", author: "Antoine de Saint-Exupéry" },
  { text: "Make it work, make it right, make it fast.", author: "Kent Beck" },
  { text: "Wachstum beginnt am Ende deiner Komfortzone.", author: "Neal Donald Walsch" },
  { text: "Debugging is twice as hard as writing the code in the first place.", author: "Brian Kernighan" },
  { text: "Disziplin ist die Brücke zwischen Zielen und Leistung.", author: "Jim Rohn" },
  { text: "The best investment you can make is an investment in yourself.", author: "Warren Buffett" },
  { text: "Measure twice, cut once.", author: "Carpenters' proverb" },
  { text: "Erfolg ist die Summe kleiner Anstrengungen, die Tag für Tag wiederholt werden.", author: "Robert Collier" },
  { text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", author: "Martin Fowler" },
  { text: "Gestern hast du gesagt, du machst es morgen.", author: "Nike" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Qualität ist kein Zufall. Sie ist immer das Ergebnis angestrengten Denkens.", author: "John Ruskin" },
  { text: "Move fast and learn things.", author: "Engineering wisdom" },
  { text: "Ein Experte ist jemand, der alle Fehler gemacht hat, die in einem sehr engen Fachgebiet gemacht werden können.", author: "Niels Bohr" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Schreibe Code, als würde ihn der nächste Maintainer ein Psychopath kennen, der weiß, wo du wohnst.", author: "John F. Woods" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Fange an, und die Kraft kommt.", author: "Goethe" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Wer aufhört, besser werden zu wollen, hört auf, gut zu sein.", author: "Philip Rosenthal" },
  { text: "The most disastrous thing that you can ever learn is your first programming language.", author: "Alan Kay" },
  { text: "Ich habe keine Misserfolge. Ich habe nur 10.000 Wege entdeckt, die nicht funktionieren.", author: "Thomas Edison" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Simplicity is a great virtue but it requires hard work to achieve it.", author: "Edsger Dijkstra" },
  { text: "Du musst nicht großartig sein, um anzufangen. Aber du musst anfangen, um großartig zu sein.", author: "Zig Ziglar" },
  { text: "Whether you think you can or you think you can't – you're right.", author: "Henry Ford" },
  { text: "The harder I work, the luckier I get.", author: "Samuel Goldwyn" },
  { text: "Träume nicht dein Leben, sondern lebe deinen Traum.", author: "Mark Twain" },
  { text: "You don't have to be perfect to start. You have to start to be perfect.", author: "Unbekannt" },
  { text: "Fall seven times, stand up eight.", author: "Japanisches Sprichwort" },
  { text: "Der Unterschied zwischen Gewöhnlichem und Außergewöhnlichem ist dieses kleine Extra.", author: "Jimmy Johnson" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "Nicht die Umstände machen den Menschen, sie enthüllen ihn.", author: "James Allen" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Wer kämpft, kann verlieren. Wer nicht kämpft, hat schon verloren.", author: "Bertolt Brecht" },
  { text: "Continuous improvement is better than delayed perfection.", author: "Mark Twain" },
  { text: "Es ist nicht zu wenig Zeit, die wir haben, sondern zu viel Zeit, die wir nicht nutzen.", author: "Seneca" },
  { text: "Small progress is still progress.", author: "Unbekannt" },
  { text: "Die größte Entdeckung meiner Generation ist, dass ein Mensch sein Leben verändern kann, indem er seine Einstellung verändert.", author: "William James" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Nur wer sein Ziel kennt, findet den Weg.", author: "Laozi" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Erfolg hat drei Buchstaben: TUN.", author: "Johann Wolfgang von Goethe" },
  { text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { text: "Was immer du tun oder träumen kannst – fange damit an.", author: "Goethe" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unbekannt" },
  { text: "Der Mensch wächst mit seinen Aufgaben.", author: "Friedrich von Schiller" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Gut ist der Feind von Großartig.", author: "Jim Collins" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Energie und Beharrlichkeit überwinden alle Dinge.", author: "Benjamin Franklin" },
  { text: "Focus on the journey, not the destination.", author: "Greg Anderson" },
  { text: "Das Geheimnis des Erfolgs ist, den Standpunkt des anderen zu verstehen.", author: "Henry Ford" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Ein Ziel ohne Plan ist nur ein Wunsch.", author: "Antoine de Saint-Exupéry" },
  { text: "Challenges are what make life interesting. Overcoming them is what makes life meaningful.", author: "Joshua J. Marine" },
  { text: "Bewege dich nicht mit der Zeit – bewege die Zeit.", author: "Unbekannt" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "Wer aufgibt, hat schon verloren.", author: "Unbekannt" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Es braucht Mut, zu wachsen und der zu werden, der du wirklich bist.", author: "E.E. Cummings" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Qualität bedeutet, das Richtige zu tun, wenn niemand zuschaut.", author: "Henry Ford" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Konfuzius" },
  { text: "Du bist der Durchschnitt der fünf Menschen, mit denen du die meiste Zeit verbringst.", author: "Jim Rohn" },
  { text: "Motivation gets you started. Habit keeps you going.", author: "Jim Ryun" },
  { text: "Sei du selbst die Veränderung, die du dir für diese Welt wünschst.", author: "Mahatma Gandhi" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "Heute ist immer der beste Tag zum Anfangen.", author: "Unbekannt" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "Vertrauen ist gut, Kontrolle ist besser – aber Loslassen ist das Beste.", author: "Unbekannt" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Die Grenzen meiner Sprache bedeuten die Grenzen meiner Welt.", author: "Ludwig Wittgenstein" },
];

export function initQuote() {
  const q = QUOTES[Math.floor(Math.random() * QUOTES.length)];
  document.getElementById('quote-text').textContent   = q.text;
  document.getElementById('quote-author').textContent = '— ' + q.author;
}
